# Generated by Django 4.2 on 2023-04-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
