# Generated by Django 4.2 on 2023-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solorapp', '0002_remove_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='rate',
            field=models.IntegerField(max_length=9),
        ),
    ]
