# Generated by Django 4.2 on 2023-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solorapp', '0003_alter_tours_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='img',
            new_name='image',
        ),
    ]
